meta_product_name: "Hobbymate"
meta_title: "Hobbymate - Find new hobbies and people to do them with"
meta_description: "Discover new hobbies and match with people who would like to join you to discover something new."
meta_image: "logo-whitecopy" # should exist in `app/assets/images/`
